### ISSUE TITLE
프로필 수정 조회 API 수정

### ISSUE THREAD

**Issue by CiC999** [codeZ-IDE/backend#46]
* 적용 페이지 : 프로필 모달

## 내용
프로필 수정 조회 코드 수정

## TODO
- [ ] User id 반환
- [ ] 프로필 수정시 권한유저인지 확인
- [ ] @Pathvariable 제외 Session으로 id 확인
- [ ] findById.get() -> findById.orElse(null)
