### ISSUE TITLE
fix/유저퀘스트 레포지토리 쿼리 수정

### ISSUE THREAD

**Issue by piczza** [codeZ-IDE/backend#51]
* 적용 페이지 : ex) 로그인 페이지

## TODO
- [x] active true만 조회되도록 쿼리 수정
- [x] 퀘스트 완료처리 api 버그 수정
- [x] 모든 엔티티에 superBuilder 패턴 도입

- **아래는 superBuilder 패턴으로 바뀐 것들**
베이스엔티티: status 디폴트값을 ACTIVE로.
User: profileIntroduce 디폴트값을 "안녕하세요!"로.
SolvingRecord: language 디폴트값을 JAVA로. isCorrect를 false로.
